package DataIn;

import java.util.List;

public class charainfo
{
    public int cid;
    public String name;
    public String title;
    public int growth;
    public int rarity;
    public int cost;
    public int jobtype;
    public int battletype;
    public int limit_break;
    public int maxlv;
    public int inihp;
    public int iniap;
    public int Aparam;
    public String skillname;
    public String skilltext;
    public int skillflag;
    public double atkspeed;
    public double movspeed;
    public double shotspeed;
    public int attackflag;
    public int motionid;
    public String spmotname;
    public int weaponid;
    public String illustrator;
    public String voice_artist;
    public String sptext;
    public int home;
    public int sup_cost;
    public int first_quest;
    public int place;
    public String profile;
    public int exp_type;
    public int skillflag0_0;
    public int skillflag0_1;
    public int skillflag1_0;
    public int skillflag1_1;
    public int bgm;
    public int chara_type;
    public List<Integer> skillid;
    public int skill_cost;
    public Double critical;
    public Integer sup1;
    public Integer sup2;
    public Integer ring;
    public Integer disp_quest;
    public Integer weaponid2;
    public Integer effectid;
    public Integer atknumber;
    public Double revision;
    public Double CRIrevision;
    public Integer CRInumber;
    public Integer master_flag;
    public Double hp_offset;

    public Double skillparam0;
    public double skillparam1;
    public Double skillparam2;
    public double skillparam3;
    public Double skillparam4;
    public Double skillparam5;
    public Double skillparam6;
    public Double skillparam7;
    public Double skillparam8;
    public Double skillparam9;

    public String str0;
    public String str1;
    public String str2;
    public String str3;
    public String str4;
    public String str5;

    public String modelname;
    public Double modelscale;
    public Integer iparam0;
    public Integer charge;
    public String chargemotion;

    public Integer pattern0;
    public Integer pattern1;
    public Integer pattern2;
    public Integer pattern3;
    public Integer pattern4;
    public Integer pattern5;
    public Integer pattern6;
    public Integer pattern7;
    public Integer pattern8;

    public Integer meet_chara;
    public Double defmagic;
    public Integer gender;
    public Integer movetype;
    public Integer is_enemy;
    public Double autoskill;
    public Integer hpflag;
    public Integer weakflag;
    public Integer defbonus;
    public Double firstautoskill;
    public Double defphysics;
    public Double atkrange;
    public Double bodyrange;
    public Integer d_autoskill;
    public Integer fd_autoskill;
    public Integer iparam1;
}